version: '3'
services:
  db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes:
        - db:/var/lib/postgresql/data

      healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
          interval: 1s
          timeout: 5s
          retries: 50  
      
  rails_app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rails_root_development
    depends_on:
       db:
          condition: service_healthy

volumes:
  db:
    driver: local
  
  rails_app:
    driver: local

